all:
  vars: ansible_ssh_user=vagrant
        ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
        ansible_ssh_common_args='-o StrictHostKeyChecking=no'
prod:
  hosts:
    app1:
      ansible_host: 192.168.1.98
    app2:
      ansible_host: 192.168.1.99
